name: ajayworkflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - feature/*
  # pull_request:
  #   branches:
  #     - main
  #     - feature/*
permissions:        
  id-token: write
  contents: read
jobs:
  ajaytest:
    name: ajaytest
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: print
        run: echo "hello world"
      - name: list files
        run: ls
      - name: read
        run: cat main.tf
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: terraform install
        uses: hashicorp/setup-terraform@v2.0.3
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan 
      - name: terraform apply
        run: terraform apply
      
          
